### ISSUE TITLE
Put Mapping 

### ISSUE THREAD

**Issue by SaiHemanth2001** [ali-bouali/spring-boot-3-jwt-security#17]
can you send the code of AuthenticationService class for putmapping

**Comment by ali-bouali** [comment]
Put mapping for what exactly?
can you elaborate?

**Comment by SaiHemanth2001** [comment]
Thanks got it long back
great tutorials you have in youtube
keep exploring and spreading knowledge

**Comment by nekitbr** [comment]
please close this issue

**Comment by SaiHemanth2001** [comment]
Ok
