### ISSUE TITLE
"Using generated security password"

### ISSUE THREAD

**Issue by Hug0C0sta** [ali-bouali/spring-boot-3-jwt-security#18]
Hello, im still having this information when i run my project and i´m having 403 in all requests that i do.
Any possible solution?
Thanks

**Comment by marcosfaneli** [comment]
How do you implement your class security?
Did your request sensed by browser? In this case you need implement Cors

**Comment by Hug0C0sta** [comment]
I made the same thing that is in the youtube video and i use postamn.

**Comment by Hug0C0sta** [comment]
I copy the code from github to my project but the issue stills the same

**Comment by marcosfaneli** [comment]
Observe if your routes are equal, the rule implemented in SecurityConfiguration.java. 
Do your log shows some error?

**Comment by mouathche** [comment]
any solution?

**Comment by andersonmadeira** [comment]
Also did the exact same thing the video showed by ended up with:
JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
and 403 For all requests

**Comment by ali-bouali** [comment]
try to make sure that you do not pass an old JWT token in the header
try to make sure that you inject all the required beans (check the annotations)

**Comment by ali-bouali** [comment]
@Hug0C0sta , is this issue still open?

**Comment by ali-bouali** [comment]
No follow up to this topic.
Closing the issue
