### ISSUE TITLE
CORS error on sending authenticated request from a different route

### ISSUE THREAD

**Issue by juliantjg** [ali-bouali/spring-boot-3-jwt-security#19]
I'm trying to call an authenticated only API from a react server on localhost:3000, and got a CORS error:
`The CORS request requires preflight, preflighting could not be performed. `. Anyone encountered this problem yet? I tried disabling the cors from the securityChainFilter but to no avail. Thanks

**Comment by marcosfaneli** [comment]
You need to add cors configuration:
1 - In method seucrityFilterChain add this:

http.csrf().disable()
        .cors().configurationSource(corsConfigurationSource())
        .and()

        ...

2 - Add this method to create your config:

private CorsConfigurationSource corsConfigurationSource() {
    final var configuration = new CorsConfiguration();

    configuration.setAllowedOriginPatterns(List.of("*"));
    configuration.setAllowedMethods(List.of("GET", "POST", "PATCH",
"PUT", "DELETE"));
    configuration.setAllowCredentials(true);
    configuration.setAllowedHeaders(List.of("Authorization",
"Cache-Control", "Content-Type"));

    final var source = new UrlBasedCorsConfigurationSource();
    source.registerCorsConfiguration("/**", configuration);

    return source;
}

*Marcos Faneli | Software Developer*
11 96411 2246
br.linkedin.com/in/marcosfaneli/pt

**Comment by ali-bouali** [comment]
as @marcosfaneli mentioned, you need to add a cors configuration if you want to access the backend from a browser (frontend application for example)
