### ISSUE TITLE
403 forbidden error while Authentication

### ISSUE THREAD

**Issue by HARSHA95336** [ali-bouali/spring-boot-3-jwt-security#20]

**Comment by wilferraciolli** [comment]
Same here, cant figure out what the issue is

**Comment by Operez97** [comment]
I had the same issue, my error was that I had duplicates in my users table.

**Comment by k-limonich** [comment]
I had the same issue. In SecurityConfig method `hasRole()` expects role to have **`ROLE_`** prefix, i.e. **`ROLE_ADMIN`**, **`ROLE_USER`**, etc. Changing method to `hasAuthority()` resolves the issue.

Checkout this answer about this issue: https://stackoverflow.com/a/48055535

**Comment by ayoubjamouhi** [comment]
Change create-drop in application.yml to update
