### ISSUE TITLE
Security Context holder is not getting Set

### ISSUE THREAD

**Issue by AdigaAkhil** [ali-bouali/spring-boot-3-jwt-security#30]
The Security Context holder is not getting set as shown in the video,  as a result of which for each request the database is looked up for token and user details.

**Comment by ali-bouali** [comment]
@AdigaAkhil  can you elaborate a bit more?
I really couldn't get the issue

**Comment by ali-bouali** [comment]
please try to post your issue in the discord server and you will for sure get the required help there.
I need to close this because it is not considered as an issue.
Thank you again

**Comment by AdigaAkhil** [comment]
Hello ali-boulai , apologies for the late reply, I was able to come up with a solution for my bug. However, it would be helpful if you could do a video on the Oauth2 login.
