### ISSUE TITLE
I see that latest commit has refresh token also added but refresh token is not saved in DB therefor client can not compare the refresh token against anything. Was this intended or it was missed?

### ISSUE THREAD

**Issue by toomas1968** [ali-bouali/spring-boot-3-jwt-security#37]

**Comment by ali-bouali** [comment]
Your point is totally valid. I just didn't save the refresh token since it is not required to be saved. It has a purpose just to refresh the JWT token so I saw that there is no need to save it and compare it.
But you can save and perform your own logic
