### ISSUE TITLE
permitAll()  Not effective

### ISSUE THREAD

**Issue by Vengxf** [ali-bouali/spring-boot-3-jwt-security#8]
permitAll url Not effective ； also can be filter by JwtAuthenticationFilter

**Comment by morsalins** [comment]
> permitAll url Not effective ； also can be filter by JwtAuthenticationFilter

If you want to avoid `JwtAuthenticationFilter` on specific url, you can just Override `shouldNotFilter` method from  `OncePerRequestFilter`. It is cleaner than checking those urls in `doFilterInternal` method.

For example:

`@Component
@Slf4j
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain) throws ServletException, IOException {
        // implement your filtering logic
    }

    @Override
    protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
        return request.getServletPath().equals("/login");
    }
}`

It returns a boolean, so you can add multiple urls, which you don't want to pass out from this filters.

**Comment by ali-bouali** [comment]
@morsalins thank you for suggestion.
Issue fixed by @morsalins
